"""
Django settings for two_decade_confections project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v_#f-f-8*wq(-s2#^z6q$ho2-jp3*6kcve9cyt=$lwrh+r%&^_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ["www.herokuapps.com","localhost:8000"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'crispy_forms',

    'products',
    'carts',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'two_decade_confections.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'two_decade_confections.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dxlofvgm',
        'USER': 'dxlofvgm',
        'PASSWORD':'rlCoWQcKFj1gITKsWcB_bBWXvTqow93S',
        'HOST': 'hard-plum.db.elephantsql.com',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

EMAIL_BACKEND = "sgbackend.SendGridBackend"
SENDGRID_API_KEY = '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'

ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
LOGIN_REDIRECT_URL = "products_list_view"

SITE_ID = 3
# SITES = ["http://localhost:8000", "http://127.0.0.1:8000"]

CRISPY_TEMPLATE_PACK = "bootstrap3"


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = ''
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    ]

MEDIA_URL = '/media/'

SOCIAL_AUTH_FACEBOOK_KEY = '1772556799703249'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET ='2b21afa826e597ee7839211c4b5a46a7' #app key

SOCIALACCOUNT_PROVIDERS = \
    {'facebook':
       {'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC':  lambda request: 'en_US',
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2.4'}}

# braintree setup
# BRAINTREE_PRIVATE='137df9b5c842c81fdff398277ff5253a'
# BRAINTREE_PUBLIC='y4gss24g5ypb3837',
# BRAINTREE_MERCHANT_ID='f3yp35zj726j2xz4'
# ENVIRONMENT='SANDBOX'

# BRAINTREE_PRIVATE='79ca5f34fbc3b9eb1157211d37731a0e'
# BRAINTREE_PUBLIC='jnpbmcwvp3v67pk6',
# BRAINTREE_MERCHANT_ID='f3yp35zj726j2xz4'
# ENVIRONMENT='SANDBOX'

# BRAINTREE_PUBLIC = 'r6k25wjjgrs85k5k'
# BRAINTREE_PRIVATE = '3e8a367a637ec65a728e2c17e582e6bb'
# BRAINTREE_MERCHANT_ID = '34hkzh8p357qypjk'
# ENVIRONMENT = 'SANDBOX'

STRIPE_API_KEY = 'sk_test_m36sZo19LZft7SAAJpQkNyli'