# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=2.99, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True)),
                ('shipping_weight', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('slug', models.SlugField(blank=True, default=None)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=4.99, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True)),
                ('active', models.BooleanField(default=True)),
                ('size', models.DecimalField(decimal_places=0, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
