# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=4.99, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True)),
                ('active', models.BooleanField(default=True)),
                ('size', models.DecimalField(decimal_places=0, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
