# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170825_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_inventory',
            field=models.IntegerField(default=100),
        ),
    ]
