# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_available_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_inventory',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
